branches:
  only:
  - master

language: r
pandoc_version: 2.2
sudo: false
dist: trusty
cache:
  packages: true
  directories:
    - $HOME/.TinyTeX

warnings_are_errors: false

r:
  - oldrel
  - release
  - devel

addons:
  apt:
    packages:
    - ghostscript

before_install:
  - wget -qO- https://github.com/yihui/tinytex/raw/master/tools/download-travis-linux.sh | sh
  - mkdir -p ~/.R
  - echo "CXX14FLAGS=-O3 -mtune=native -march=native -Wno-unused-variable -Wno-unused-function  -Wno-macro-redefined" >> ~/.R/Makevars
  - echo "CXX14=g++ -std=c++1y -fPIC" >> ~/.R/Makevars

env:
  global:
    - R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
